spring:
  application:
    name: spring-boot-rest-api
  datasource:
    url: jdbc:h2:mem:spring-boot-rest-api-demo
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update